@startuml ComponentDiagram
skinparam linetype ortho
package "SwitchBotController System" {
    
    [AutoSwitchControlUseCase] as Controller
    [InputPort] <<interface>>
    [SwitchControlPort] <<interface>>
    [Sensor] <<abstract>>
    [VCNL4040Sensor]
    [SensorAdapter]
    [SwitchBotApiClient]
    
    Controller ..|> InputPort : impl
    SensorAdapter --> InputPort : uses
    
    Controller --> SwitchControlPort : uses
    SwitchBotApiClient ..|> SwitchControlPort : impl
    
    VCNL4040Sensor --|> Sensor
    SensorAdapter --> Sensor : uses
}

@enduml 